EECS2311/EECS2311

.classpath
.gitignore
src/FirstClass.java

Set up the java project, please review.
Setup on Java17

Setup Java Project

---

.classpath
.gitignore
src/FirstClass.java
src/Item.java

Create Item class with some attributes and methods.
Pulled from `test` branch.

Create Item class

---

src/AddItemPanel.java
src/AddItemPanelDemo.java

Created:
- AddItemPanel UI Class
- AddItemPanelDemo to run AddItemPanel in a JFrame

Add item UI

---

src/demo/AddItemPanelDemo.java
src/domain/logic/Container.java
src/domain/logic/FoodFreshness.java
src/domain/logic/FoodGroup.java
src/domain/logic/GenericTag.java
src/domain/logic/Item.java
src/domain/logic/Tag.java
src/domain/logic/TagUtility.java
src/gui/AddItemPanel.java
src/gui/ContainerView.java
src/gui/Home.java
src/test/ItemTest.java
src/test/TagsTest.java

Moves files into their respective packages

Make new packages

---

src/database/DB.java
src/test/ItemTest.java

Added database class + package

Updated database class + refactor

---

src/database/DB.java
src/gui/ContainerView.java
src/gui/DeleteItemView.java
src/gui/Itemslist.java

Add and Delete functionality now fully connected, Nina provided some code to search for rows based on name of item

Delete items removes from database

---

src/test/DeleteItemViewTest.java

Created test case for deleting item

Quick Test for removing items

---

src/domain/logic/Item.java
src/test/ItemTest.java

Completed Junit test for Item class. 
It has normal cases and edge cases.

Item testing

---

src/database/initSchema.sql

Just setup a basic database schema for our current implementation

Updated Basic database schema

---

src/domain/logic/DeleteItem.java
src/gui/DeleteItemView.java
src/gui/HomeView.java

Just separated the GUI and logic for the deleteItem

Separate logic and GUI for delete item view

---

src/database/initSchema.sql
src/gui/DeleteItemView.java

Just cleaned up delete item view class + updated sql file.

Added Slight Update

---

src/gui/ContainerView.java
src/gui/HomeView.java

Changed the gui for homeview, also chnaged the call from itemsView from initialiseHomeGUI to changeStageOfHome, got rid of initialiseHomeGUI

Changed HomeView GUI

---

src/gui/HomeView.java

Changed frame size to 800*600, changed panel size correspondingly

Home view edits

---

src/database/DB.java
src/gui/HomeView.java

Refactored homeview to make db integration easier. PR'd just to fix some merge conflicts on github

Added new methods, refactor homeview

---

src/database/DB.java
src/domain/logic/ContainerUtility.java
src/gui/HomeView.java
src/test/AddContainerTest.java

Integrated the database with the add container method. 
- Added error handling for duplicate containers
- Setup Container utility class to separate logic from gui 
- Added quick integration test

Integrate db

---

src/gui/ContainerView.java
src/gui/DeleteContainerView.java
src/gui/EditContainerView.java
src/gui/HomeView.java
src/gui/SeeContainersView.java

Added 3 classes; SeeContainersView, EditContainerView, DeleteContainerView to replace stages in HomeView

Refactor home view

---

src/database/DB.java
src/domain/logic/ItemUtility.java
src/gui/EnumComboBoxEditor.java
src/gui/ItemsListView.java

- Items are colour coded based on FoodFreshness
Red = Expired
Yellow = Near_Expiry
Green = Fresh

Colour code item

---

src/database/DB.java

Food item expiry date the same as the current date will be Near_Expiry and not Fresh

Fix small typo on batchUpdateItemFreshness

---

src/domain/logic/ItemUtility.java
src/gui/AddItemView.java
src/gui/EnumComboBoxEditor.java
src/gui/ItemsListView.java
src/test/ContainerTest.java
src/test/ItemUtilityTest.java

Added Junit tests for Container and ItemUtility

Add Unit tests and refactor ItemUtility methods

---

src/gui/HomeView.java

Notification pops up with home view

notfication works with home view

---

src/database/DB.java
src/database/StubDB.java
src/domain/logic/recipe/RecipeUtility.java
src/gui/HomeView.java
src/gui/RecipeDetailView.java
src/gui/RecipeListView.java
src/test/unit/IngredientTest.java
src/test/unit/RecipeTest.java

Created RecipeListView and RecipeDetailView
Will need gson and SpoonacularAPI.

Recipe gui

---

src/domain/logic/ItemUtility.java
src/gui/AddItemView.java

Solves:
[Bug Report: Incorrect error messages for AddItemView #106](https://github.com/EECS2311/EECS2311/issues/106)
[Bug Report: Expired Items can be added #107](https://github.com/EECS2311/EECS2311/issues/107)

Fix error messages when adding items

---

src/database/DB.java
src/domain/logic/StatsUtilities.java
src/gui/GroceryListView.java
src/gui/HomeView.java
src/gui/RecipeListView.java
src/gui/SeeContainersView.java
src/gui/StatsDesc.java
src/gui/StatsRectangle.java
src/gui/StatsView.java

Implement statistics for food item composition for all pantries and individual pantries

Statistics

---

src/gui/ItemsListView.java

Resolve Bug Report: Table coloumns are moveable #112

Prevent table columns from moving

---

src/gui/Additemhome.java
src/gui/HomeView.java

Additemfromhome

---

src/database/StubDB.java
src/gui/home/HomeView.java
src/gui/home/SettingsView.java

Added fonts to homeView and updated its components bounds for different font sizes

Fonts added to home view

---

src/gui/Additemhome.java
src/gui/add_items/ActionListenerManager.java
src/gui/add_items/AddItemView.java
src/gui/add_items/CustomColorCodedTable.java
src/gui/add_items/CustomTableModel.java
src/gui/add_items/ItemsListView.java

Resolves Code Review: Large Class for ItemListView #124

Refactor ItemsListView

---

src/gui/statistics/StatsDescView.java
src/gui/statistics/StatsView.java

Added font support to Statistics View

Added font support for Statistics View

---

src/database/DB.java
src/domain/logic/item/ItemUtility.java
src/gui/add_items/ActionListenerManager.java
src/gui/add_items/ItemsListView.java
src/gui/home/HomeView.java
src/test/integration/ItemUtilityDBTest.java
src/test/unit/ItemUtilityTest.java

Add integration test for RecipeUtility

Item utility test

---

src/gui/home/HomeView.java

Fixed multiple dialogs bug
